services:
  yivi_consent_node:
    build:
      context: ./yivi-consent-node
      args:
        VITE_YIVI_BACKEND_URL: ${VITE_YIVI_BACKEND_URL}
        VITE_YIVI_FRONTEND_DEBUG: ${VITE_YIVI_FRONTEND_DEBUG}
    env_file: ./yivi-consent-node/.env
    environment:
      - HYDRA_ADMIN_URL=${HYDRA_ADMIN_URL}
      - IRMA_SERVER_URL=${IRMA_SERVER_URL}
      - IRMA_SERVER_TOKEN=${IRMA_SERVER_TOKEN}
      - YIVI_BACKEND_DEBUG=${YIVI_BACKEND_DEBUG}
      - PORT=${PORT}
    ports:
      - "${PORT}:3000"
    networks:
      - yivi-oidc-network

  irma_server:
    image: ghcr.io/privacybydesign/irma:latest
    command: server --verbose --jwt-privkey-file /irmago/config/private.pem --url "${IRMA_SERVER_PUBLIC_URL}"
    ports:
      - "8088:8088"
    volumes:
      - ${YIVI_RUNTIME_DIR}:/irmago/config:ro,z
    networks:
      - yivi-oidc-network

  hydra:
    image: oryd/hydra:v2.3.0
    ports:
      - "4444:4444"
      - "4445:4445"
      - "5555:5555"
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    environment:
      - DSN=${HYDRA_DSN}
      - SECRETS_SYSTEM=${HYDRA_SECRETS_SYSTEM}
      - URLS_SELF_ISSUER=${HYDRA_ISSUER_URL}
      - URLS_SELF_PUBLIC=${HYDRA_SELF_PUBLIC_URL}
      - URLS_CONSENT=${HYDRA_CONSENT_URL}
      - URLS_LOGIN=${HYDRA_LOGIN_URL}
      - URLS_LOGOUT=${HYDRA_LOGOUT_URL}
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=${HYDRA_SUBJECT_PAIRWISE_SALT}
    volumes:
      - ./yivi-consent-node/config/hydra:/etc/config/hydra:ro,z
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully
        restart: false
      postgresd_hydra:
        condition: service_healthy
        restart: false
    networks:
      - yivi-oidc-network

  hydra-migrate:
    image: oryd/hydra:v2.3.0
    command: migrate -c /etc/config/hydra/hydra.yml sql up -e --yes
    environment:
      - DSN=${HYDRA_DSN}
      - SECRETS_SYSTEM=${HYDRA_SECRETS_SYSTEM}
    restart: on-failure
    volumes:
      - ./yivi-consent-node/config/hydra:/etc/config/hydra:ro,z
    depends_on:
      postgresd_hydra:
        condition: service_healthy
        restart: false
    networks:
      - yivi-oidc-network

  postgresd_hydra:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${HYDRA_POSTGRES_DB}
      - POSTGRES_USER=${HYDRA_POSTGRES_USER}
      - POSTGRES_PASSWORD=${HYDRA_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${HYDRA_POSTGRES_USER} -d ${HYDRA_POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-hydra-data:/var/lib/postgresql/data
    networks:
      - yivi-oidc-network

volumes:
  postgres-hydra-data:

networks:
  yivi-oidc-network:
