# include:
#   - ../vendor/irmago/docker-compose.yml

# Domains for demo production
# demo-app.dennisgabeler.nl: Demo application acting as the OIDC client
# oidc.dennisgabeler.nl: OIDC endpoint to which OIDC clients will connect to
# yivi.dennisgabeler.nl: Yivi frontend used in the Yivi authentication flow
# yivi-server.dennisgabeler.nl: Yivi/IRMA server handling Yivi sessions for disclosure requests

services:
  proxy:
    image: caddy:2.10.0-alpine
    ports:
      - "443:443"
      - "443:443/udp"
      - "80:80"
      - "80:80/udp"
    volumes:
      - ./yivi-consent-node/config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro,z
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - yivi-oidc-network
  yivi_consent_node:
    build: ./yivi-consent-node
    networks:
      - yivi-oidc-network
  irma_server:
    build: ./vendor/irmago/
    command: server -vv --jwt-privkey-file /irmago/config/private.pem --url "https://yivi-server.dennisgabeler.nl" -p 8088 --production --no-email true --config /irmago/config/irmaserver.json
    volumes:
      - ./yivi-consent-node/config/yivi:/irmago/config:ro,z
    networks:
      - yivi-oidc-network
  hydra:
    env_file: ./yivi-consent-node/.env.production.local
    image: oryd/hydra:v2.3.0
    command: serve -c /etc/config/hydra/hydra-prod.yml all
    environment:
      - SECRETS_SYSTEM=${SECRETS_SYSTEM} 
      - DSN=${HYDRA_DSN}
    restart: unless-stopped
    volumes:
      - ./yivi-consent-node/config/hydra:/etc/config/hydra:ro,z
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully
        restart: false
      postgresd_hydra:
        condition: service_healthy
        restart: false
    networks:
      - yivi-oidc-network
  hydra-migrate:
    env_file: ./yivi-consent-node/.env.production.local
    image: oryd/hydra:v2.3.0
    environment:
      - DSN=${HYDRA_DSN}
    command: migrate -c /etc/config/hydra/hydra-prod.yml sql up -e --yes
    restart: on-failure
    volumes:
      - ./yivi-consent-node/config/hydra:/etc/config/hydra:ro,z
    depends_on:
      postgresd_hydra:
        condition: service_healthy
        restart: false
    networks:
      - yivi-oidc-network
  postgresd_hydra:
      env_file: ./yivi-consent-node/.env.production.local
      image: postgres:17.4
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=hydra
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ory -d hydra"]
        interval: 2s
        timeout: 5s
        retries: 10
      volumes:
        - postgres-hydra-data:/var/lib/postgresql/data
      networks:
        - yivi-oidc-network
volumes:
  postgres-hydra-data:
  caddy_data:
  caddy_config:
networks:
  yivi-oidc-network:
