# include:
#   - ../vendor/irmago/docker-compose.yml
services:
  yivi_consent_node:
    build: ./yivi-consent-node
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
      - IRMA_SERVER_URL=http://irma_server:8088
    ports: 
      - 3000:3000
    networks:
      - yivi-oidc-network
  irma_server:
    image: ghcr.io/privacybydesign/irma:latest
    command: server --verbose --jwt-privkey-file /irmago/config/private.pem --url "http://145.137.161.80:8088"
    ports:
      - 8088:8088
    volumes:
      - ./yivi-consent-node/config/yivi:/irmago/config:ro,z
    networks:
      - yivi-oidc-network
  hydra:
    image: oryd/hydra:v2.3.0
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    environment: 
       - DSN=postgres://ory:secret@postgresd_hydra:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
       - SECRETS_SYSTEM=Sj2ypq-TJi9NjgWW10FhtE-BgOpVaWJB
       - URLS_SELF_ISSUER=http://localhost:4444
       - URLS_SELF_PUBLIC=http://localhost:4444/
       - URLS_CONSENT=http://127.0.0.1:3000/consent
       - URLS_LOGIN=http://127.0.0.1:3000/login
       - URLS_LOGOUT=http://127.0.0.1:3000/logout
    volumes:
      - ./yivi-consent-node/config/hydra:/etc/config/hydra:ro,z
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully
        restart: false
      postgresd_hydra:
        condition: service_healthy
        restart: false
    networks:
      - yivi-oidc-network
  hydra-migrate:
    image: oryd/hydra:v2.3.0
    command: migrate -c /etc/config/hydra/hydra.yml sql up -e --yes
    environment:
      - DSN=postgres://ory:secret@postgresd_hydra:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=Sj2ypq-TJi9NjgWW10FhtE-BgOpVaWJB
    restart: on-failure
    volumes:
      - ./yivi-consent-node/config/hydra:/etc/config/hydra:ro,z
    depends_on:
      postgresd_hydra:
        condition: service_healthy
        restart: false
    networks:
      - yivi-oidc-network
  postgresd_hydra:
      image: postgres:16.3
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=hydra
        - POSTGRES_USER=ory
        - POSTGRES_PASSWORD=secret
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ory -d hydra"]
        interval: 2s
        timeout: 5s
        retries: 10
      volumes:
        - postgres-hydra-data:/var/lib/postgresql/data
      networks:
        - yivi-oidc-network
volumes:
  postgres-hydra-data:
networks:
  yivi-oidc-network:
