# include:
#   - ../vendor/irmago/docker-compose.yml
services:
  irma_server:
    image: ghcr.io/privacybydesign/irma:latest
    command: server --verbose --jwt-privkey-file /irmago/config/private.pem --url "http://145.116.164.223:port"
    ports:
      - 8088:8088
    volumes:
      - type: bind
        source: ./config
        target: /irmago/config
    networks:
      - yivi-oidc-network
networks:
  yivi-oidc-network: