services:
  proxy:
    networks:
      - intranet
  ory_auth_demo:
    build:
      context: ./examples/kratos-yivi/ory_auth_demo
      dockerfile: ./Dockerfile
    networks:
      - intranet
  kratos-migrate:
    image: oryd/kratos:v1.3.0
    env_file:
      - path: ./examples/kratos-yivi/.env
        required: true
    command: -c /etc/config/kratos/kratos-prod.yml migrate sql -e --yes
    restart: on-failure
    volumes:
      - ./examples/kratos-yivi/config/kratos:/etc/config/kratos:ro,z
    depends_on:
      postgresd_kratos:
        condition: service_healthy
        restart: false
    networks:
      - intranet
  kratos-selfservice-ui-node:
    build:
      context: ./vendor/kratos-selfservice-ui-node
      dockerfile: ./Dockerfile
    image: oryd/kratos-selfservice-ui-node:v1.1.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=https://demo-app.dennisgabeler.nl/
      - HYDRA_ADMIN_URL=http://hydra:4445/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - PORT=4455
      - SECURITY_MODE=
    networks:
      - intranet
      - yivi-oidc-network
    restart: on-failure
  kratos:
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
        restart: false
      postgresd_kratos:
        condition: service_healthy
        restart: false
    image: oryd/kratos:v1.3.0
    restart: unless-stopped
    env_file: ./examples/kratos-yivi/.env
    environment:
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos-prod.yml
    volumes:
      - ./examples/kratos-yivi/config/kratos:/etc/config/kratos:ro,z
    networks:
      - intranet
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    networks:
      - intranet
  postgresd_kratos:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=kratos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ory -d kratos"]
      interval: 2s
      timeout: 5s
      retries: 10
    networks:
      - intranet
    volumes:
      - postgres-kratos-data:/var/lib/postgresql/data
networks:
  intranet:
volumes:
  postgres-kratos-data:
