version: "3.7"
services:
  hydra:
    image: oryd/hydra:v2.2.0
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    # command: serve -c /etc/config/hydra/hydra.yml all --dev
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/hydra
    # volumes:
      # - type: volume
      #   source: hydra-sqlite
      #   target: /var/lib/sqlite
      #   read_only: false
      # - type: bind
      #   source: ./contrib/quickstart/5-min
      #   target: /etc/config/hydra
    environment:
      - SECRETS_SYSTEM=${SECRETS_SYSTEM}
      - DSN=${HYDRA_DSN}
      # - URLS_SELF_ISSUER=https://localhost:4444/
      # - URLS_CONSENT=http://localhost:3000/consent
      # - URLS_LOGIN=http://localhost:3000/login
    restart: unless-stopped
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully
        restart: false
      postgresd_hydra:
        condition: service_started
        restart: false
    networks:
      - intranet
  hydra-migrate:
    image: oryd/hydra:v2.2.0
    environment:
      - DSN=${HYDRA_DSN}
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    restart: on-failure
    networks:
      - intranet
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/hydra
    depends_on:
      postgresd_hydra:
        condition: service_started
        restart: false
  postgresd_hydra:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=hydra
    volumes:
      - postgres-hydra-data:/var/lib/postgresql/data
    networks:
      - intranet
  yivi-consent-node:
    build: hydra-login-consent-node
    ports:
      - "3000:3000" # Public port
    networks:
      - intranet
  ory_auth_demo:
    build: ory_auth_demo
    ports:
      - "4000:4000" # Public port
    networks:
      - intranet
  kratos-migrate:
    image: oryd/kratos:v1.1.0
    environment:
      - DSN=${KRATOS_DSN}
    volumes:
      - type: bind
        source: ./config/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    depends_on:
      postgresd_kratos:
        condition: service_started
        restart: false
    networks:
      - intranet
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.1.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - HYDRA_ADMIN_URL=http://hydra:4445/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - PORT=4455
      - SECURITY_MODE=
    ports:
      - "4455:4455"
    networks:
      - intranet
    restart: on-failure
  kratos:
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
        restart: false
      postgresd_kratos:
        condition: service_started
        restart: false
    image: oryd/kratos:v1.1.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=${KRATOS_DSN}
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config/kratos
        target: /etc/config/kratos
    networks:
      - intranet
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
  postgresd_kratos:
    image: postgres:16.2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=kratos
    networks:
      - intranet
    volumes:
      - postgres-kratos-data:/var/lib/postgresql/data
    

networks:
  intranet:
volumes:
  postgres-hydra-data:
  postgres-kratos-data: