version: "3.7"
services:
  # yivi-consent-node:
  #   build: hydra-login-consent-node
  #   ports:
  #     - "3000:3000" # Public port
  #   networks:
  #     - intranet
  ory_auth_demo:
    build: ory_auth_demo
    ports:
      - "4000:4000" # Public port
    networks:
      - intranet
  kratos-migrate:
    image: oryd/kratos:v1.1.0
    environment:
      - DSN=${KRATOS_DSN}
    volumes:
      - type: bind
        source: ./config/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    depends_on:
      postgresd_kratos:
        condition: service_started
        restart: false
    networks:
      - intranet
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.1.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - HYDRA_ADMIN_URL=http://hydra:4445/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - PORT=4455
      - SECURITY_MODE=
    ports:
      - "4455:4455"
    networks:
      - intranet
    restart: on-failure
  kratos:
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
        restart: false
      postgresd_kratos:
        condition: service_started
        restart: false
    image: oryd/kratos:v1.1.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=${KRATOS_DSN}
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config/kratos
        target: /etc/config/kratos
    networks:
      - intranet
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
  postgresd_kratos:
    image: postgres:16.2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=kratos
    networks:
      - intranet
    volumes:
      - postgres-kratos-data:/var/lib/postgresql/data
    

networks:
  intranet:
volumes:
  postgres-hydra-data:
  postgres-kratos-data: