serve:
  # public:
  #   cors: 
  #     enabled: true
  cookies:
    same_site_mode: Lax

webfinger:
  oidc_discovery:
    supported_claims:
      - email # email scope
      - name # profile scope
    supported_scope:
      - email
      - profile

oauth2:
  expose_internal_errors: true

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public