serve:
  cookies:
    same_site_mode: Lax

webfinger:
  oidc_discovery:
    supported_claims:
      - email # email scope
      - name # profile scope
    supported_scope:
      - email
      - profile
    # auth_url: http://hydra:4444/oauth2/auth
oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public