version: v0.13.0

dsn: postgres://ory:secret@postgresd_kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4000/
  allowed_return_urls:
    - http://127.0.0.1:4000
    - http://127.0.0.1:4455
    - http://localhost:19006/Callback
    - exp://localhost:8081/--/Callback

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      config:
        providers:
          - id: linkedin
            provider: generic
            client_id: 78y8yopnonfa3n
            client_secret: MHrQ5iBF110wCoJr
            issuer_url: https://www.linkedin.com/oauth
            mapper_url: "base64://bG9jYWwgY2xhaW1zID0gewogIGVtYWlsX3ZlcmlmaWVkOiBmYWxzZSwKfSArIHN0ZC5leHRWYXIoJ2NsYWltcycpOwp7CiAgaWRlbnRpdHk6IHsKICAgIHRyYWl0czogewogICAgICAvLyBBbGxvd2luZyB1bnZlcmlmaWVkIGVtYWlsIGFkZHJlc3NlcyBlbmFibGVzIGFjY291bnQKICAgICAgLy8gZW51bWVyYXRpb24gYXR0YWNrcywgIGlmIHRoZSB2YWx1ZSBpcyB1c2VkIGZvcgogICAgICAvLyB2ZXJpZmljYXRpb24gb3IgYXMgYSBwYXNzd29yZCBsb2dpbiBpZGVudGlmaWVyLgogICAgICAvLwogICAgICAvLyBUaGVyZWZvcmUgd2Ugb25seSByZXR1cm4gdGhlIGVtYWlsIGlmIGl0IChhKSBleGlzdHMgYW5kIChiKSBpcyBtYXJrZWQgdmVyaWZpZWQKICAgICAgLy8gYnkgTGlua2VkSW4uCiAgICAgIFtpZiAnZW1haWwnIGluIGNsYWltcyAmJiBjbGFpbXMuZW1haWxfdmVyaWZpZWQgdGhlbiAnZW1haWwnIGVsc2UgbnVsbF06IGNsYWltcy5lbWFpbCwKICAgIH0sCiAgfSwKfQ=="
            scope:
              - email
              - profile
              - openid
          - id: yivi
            provider: generic
            client_id: c5f471dc-c7dd-4a0d-8ab3-c665104d4a97
            client_secret: wpHIh0Qi.eNU5Q4TST9bI1eDz7
            issuer_url: http://host.docker.internal:4444/
            # mapper_url: "base64://bG9jYWwgY2xhaW1zID0gc3RkLmV4dFZhcignY2xhaW1zJyk7CnsKICBpZGVudGl0eTogewogICAgdHJhaXRzOiB7CiAgICAgIC8vIEFsbG93aW5nIHVudmVyaWZpZWQgZW1haWwgYWRkcmVzc2VzIGVuYWJsZXMgYWNjb3VudAogICAgICAvLyBlbnVtZXJhdGlvbiBhdHRhY2tzLCAgaWYgdGhlIHZhbHVlIGlzIHVzZWQgZm9yCiAgICAgIC8vIHZlcmlmaWNhdGlvbiBvciBhcyBhIHBhc3N3b3JkIGxvZ2luIGlkZW50aWZpZXIuCiAgICAgIC8vCiAgICAgIC8vIElmIGNvbm5lY3Rpbmcgb25seSB0byB5b3VyIG9yZ2FuaXphdGlvbiAob25lIHRlbmFudCksIGNsYWltcy5lbWFpbCBpcyBzYWZlIHRvIHVzZQogICAgICAvLyBpZiB5b3UgaGF2ZW4ndCBhY3RpdmVseSBkaXNhYmxlZCBlLW1haWwgdmVyaWZpY2F0aW9uIGR1cmluZyBzaWduLXVwLgogICAgICAvLwogICAgICAvLyBUaGUgZW1haWwgbWlnaHQgYmUgZW1wdHkgaWYgdGhlIGFjY291bnQgaXNuJ3QgbGlua2VkIHRvIGFuIGVtYWlsIGFkZHJlc3MuCiAgICAgIC8vIEZvciBhIGh1bWFuIHJlYWRhYmxlIGlkZW50aWZpZXIsIGNvbnNpZGVyIHVzaW5nIHRoZSAicHJlZmVycmVkX3VzZXJuYW1lIiBjbGFpbS4KICAgICAgW2lmICdlbWFpbCcgaW4gY2xhaW1zIHRoZW4gJ2VtYWlsJyBlbHNlIG51bGxdOiBjbGFpbXMuZW1haWwsCiAgICB9LAogIH0sCn0="
            mapper_url: "base64://bG9jYWwgY2xhaW1zID0gc3RkLmV4dFZhcignY2xhaW1zJyk7CnsKICBpZGVudGl0eTogewogICAgdHJhaXRzOiB7CiAgICAgIFtpZiAnZW1haWwnIGluIGNsYWltcyB0aGVuICdlbWFpbCcgZWxzZSBudWxsXTogY2xhaW1zLmVtYWlsLAogICAgICBuYW1lOiB7CiAgICAgICAgICBbaWYgJ2dpdmVuX25hbWUnIGluIGNsYWltcyB0aGVuICdmaXJzdCcgZWxzZSBudWxsXTogY2xhaW1zLmdpdmVuX25hbWUsCiAgICAgICAgICBbaWYgJ2ZhbWlseV9uYW1lJyBpbiBjbGFpbXMgdGhlbiAnbGFzdCcgZWxzZSBudWxsXTogY2xhaW1zLmZhbWlseV9uYW1lCiAgICAgIH0KICAgIH0sCiAgfSwKfQ=="
            scope:
              - email
              - phone
              - openid
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/login

    login:
      ui_url: http://127.0.0.1:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

feature_flags:
  use_continue_with_transitions: true
